routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth', 'allowed']], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::group(['namespace' => 'Admin'], function () {
        Route::resource('permission', 'PermissionController');
        Route::resource('role', 'RoleController');
        Route::resource('user', 'UserController');
    });
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\RolesDataTable;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(RolesDataTable $rolesDataTable)
    {
        return $rolesDataTable->render('admin.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Role $role)
    {
        $permissions = Permission::orderBy('name', 'asc')->get();
        return view('admin.roles.create', compact('role', 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = Role::create($request->validate($this->rules(), $this->message()));
        $role->givePermissionTo(Permission::whereIn('id', $request->permissions)->get());
        return redirect(route('role.index'))->with('success', 'Inserted Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Role $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::orderBy('name', 'asc')->get();
        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Role $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $role->update($request->validate($this->rules($role->id), $this->message()));
        $role->givePermissionTo(Permission::whereIn('id', $request->permissions)->get());
        return redirect(route('role.index'))->with('success', 'Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Role $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        return response(['success' => true, 'message' => 'Role Deleted'], 200);
    }

    public function rules($id = 0)
    {
        return [
            'name' => "required|string|max:255|unique:roles,name,{$id},id",
            'guard_name' => "required|string|max:255",
            'permissions.*' => ["required", "exists:permissions,id"]
        ];
    }

    public function message()
    {
        return [];
    }
}

resources/views/admin/roles/action.blade.php
<div class="d-flex">
    <a href="{{ route('role.edit', $model->id) }}" class="btn btn-warning btn-sm mx-1">
        <i class="fas fa-pencil-alt"></i>
    </a>
    @csrf
    <a href="#" class="btn btn-danger btn-sm mx-1"
        onclick="window.deleteData(event,'{{ route('role.destroy', $model->id) }}');">
        <i class="fa fa-trash" aria-hidden="true"></i>
    </a>
</div>

resources/views/admin/roles/create.blade.php
@extends('layouts.main',['name' => 'home'])
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link" href="{!!  route('role.index') !!}">
                                <i class="ion ion-ios-list-outline mr-2"></i>{{ __('Roles') }}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{!!  route('role.create') !!}">
                                <i class="ion ion-plus mr-2"></i>{{ __('Create') }}
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <form action="{{ route('role.store') }}" method="post">
                        @include('admin.roles.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.main',['name' => 'home'])
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('role.update', $role->id) }}" method="post">
                        @method('patch')
                        @include('admin.roles.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/form.blade.php
@csrf
<div class="form-group">
    <label for="name">Role Name</label>
    <input type="text" name="name" id="name" value="{{ old('name') ?? $role->name }}"
        class="form-control @error('name') is-invalid @enderror" placeholder="Role name">
    @error('name')
        <div class="invalid-feedback">
            <strong>{{ $message }}</strong>
        </div>
    @enderror
</div>
<div class="form-group">
    <label for="guard_name">Middleware Group</label>
    <input type="text" name="guard_name" id="guard_name" value="{{ old('guard_name') ?? $role->guard_name }}"
        class="form-control @error('guard_name') is-invalid @enderror" placeholder="Middleware group Default is WEB">
    @error('guard_name')
        <div class="invalid-feedback">
            <strong>{{ $message }}</strong>
        </div>
    @enderror
</div>
<div class="form-group">
    <label for="permissions">Permissions</label>
    <select multiple class="form-control multiSelect @error('permissions') is-invalid @enderror" name="permissions[]" id="permissions">
        @foreach ($permissions as $permission)
            <option value="{{ $permission->id }}" 
                @foreach ((old('permissions') ?? $role->permissions) as $item)
                    {{(old('permissions') ?$item : $item->id)  == $permission->id ? 'selected' : null}} 
                @endforeach
                >{{ $permission->name }}</option>
        @endforeach
    </select>
    @error('permissions')
        <div class="invalid-feedback">
            <strong>{{ $message }}</strong>
        </div>
    @enderror
</div>
<button class="btn btn-primary w-100">Submit</button>

resources/views/admin/roles/index.blade.php
`@extends('layouts.main',['name' => 'home'])
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" href="{!!  route('role.index') !!}">
                                <i class="ion ion-ios-list-outline mr-2"></i>{{ __('Roles') }}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{!!  route('role.create') !!}">
                                <i class="ion ion-plus mr-2"></i>{{ __('Create') }}
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="card-body table-responsive">
                    {{ $dataTable->table() }}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    {{ $dataTable->scripts() }}
@endsection