routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth', 'allowed']], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::group(['namespace' => 'Admin'], function () {
        Route::resource('permission', 'PermissionController');
        Route::resource('role', 'RoleController');
        Route::resource('user', 'UserController');
    });
});

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\PermissionsDataTable;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PermissionsDataTable $permissionsDataTable)
    {
        return $permissionsDataTable->render('admin.permissions.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Permission $permission)
    {
        return view('admin.permissions.create', compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate($this->rules(), $this->message());
        Permission::create($validated);
        return redirect(route('permission.index'))->with('success', 'Inserted Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        return view('admin.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $permission->update($request->validate($this->rules($permission->id), $this->message()));
        return redirect(route('permission.index'))->with('success', 'Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy($permission)
    {
        $permission = Permission::findById($permission);
        if (!$permission) {
            return response(['success' => false, 'message' => 'Data not found'], 404);
        }
        return response(['success' => $permission->delete(), 'message' => 'Data deleted'], 200);
    }

    public function rules($id = 0)
    {
        return [
            'name' => "required|string|max:255|unique:permissions,name,{$id},id",
            'guard_name' => "required|string|max:255",
        ];
    }

    public function message()
    {
        return [];
    }
}

resources/views/admin/permissions/action.blade.php
<div class="d-flex">
    <a href="{{ route('permission.edit', $model->id) }}" class="btn btn-warning btn-sm mx-1">
        <i class="fas fa-pencil-alt"></i>
    </a>
    @csrf
    <a href="#" class="btn btn-danger btn-sm mx-1"
        onclick="window.deleteData(event,'{{ route('permission.destroy', $model->id) }}');">
        <i class="fa fa-trash" aria-hidden="true"></i>
    </a>
</div>

resources/views/admin/permissions/create.blade.php
@extends('layouts.main',['name' => 'home'])
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link" href="{!!  route('permission.index') !!}">
                                <i class="ion ion-ios-list-outline mr-2"></i>{{ __('Permission') }}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{!!  route('permission.create') !!}">
                                <i class="ion ion-plus mr-2"></i>{{ __('Create') }}
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <form action="{{ route('permission.store') }}" method="post">
                        @include('admin.permissions.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/permissions/edit.blade.php
@extends('layouts.main',['name' => 'home'])
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('permission.update', $permission->id) }}" method="post">
                        @method('patch')
                        @include('admin.permissions.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/permissions/form.blade.php
    @csrf
    <div class="form-group">
        <label for="name">Permission Name</label>
        <input type="text" name="name" id="name" value="{{ old('name') ?? $permission->name }}"
            class="form-control @error('name') is-invalid @enderror" placeholder="Permission name">
        @error('name')
            <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </div>
        @enderror
    </div>
    <div class="form-group">
        <label for="guard_name">Middleware Group</label>
        <input type="text" name="guard_name" id="guard_name" value="{{ old('guard_name') ?? $permission->guard_name }}"
            class="form-control @error('guard_name') is-invalid @enderror"
            placeholder="Middleware group Default is WEB">
        @error('guard_name')
            <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </div>
        @enderror
    </div>
    <button class="btn btn-primary w-100">Submit</button>

resources/views/admin/permissions/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" href="{!!  route('permission.index') !!}">
                                <i class="ion ion-ios-list-outline mr-2"></i>{{ __('Permission') }}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{!!  route('permission.create') !!}">
                                <i class="ion ion-plus mr-2"></i>{{ __('Create') }}
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="card-body table-responsive">
                    {{ $dataTable->table() }}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    {{ $dataTable->scripts() }}
@endsection